# .codecov.yml configuration for a small open source project

codecov:
  notify:
    require_ci_to_pass: yes
    after_n_builds: 1

coverage:
  status:
    project:
      default:
        # Set the minimum coverage percentage required
        target: 65%
        threshold: 5%
    patch:
      default:
        # Set a more reasonable patch coverage target
        target: 65%
        threshold: 5%

  precision: 2 # Report coverage numbers with a precision of 2 decimal places
  round: down # Round coverage numbers down

  # Define a threshold below which the coverage is considered poor
  threshold: 1%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: False
  require_base: False
  require_head: False
  require_report: False

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

flags:
  unittest: # Define a flag for unit tests
    paths:
      - "tests/unit"
  integration: # Define a flag for integration tests
    paths:
      - "tests/integration"

# Ignore files and directories that should not be included in coverage
ignore:
  - "node_modules/*"
  - "vendor/*"
  - "docs/*"
  - "**/*.md"
  - "**/*Tests.*" # Ignore any project with 'Tests.' in its name

# Settings for custom coverage reporting
yaml:
  min_version: "1.0.0"

# Configuration for how the coverage reports are uploaded
upload:
  # Define the method for uploading coverage reports
  method: "post"
  max_upload_size: 300
  compression: true
  chunk_size: 1000

# Repository settings
repository:
  owner: "paulegradie"
  name: "Sailfish"
  branch: "main"
  commit: "HEAD"
  pr: "auto"
