namespace Sailfish.Analysis.Scalefish;

public record ComplexityResult(IComplexityFunction ComplexityFunction, double GoodnessOfFit, IComplexityFunction NextClosestComplexity, double NextClosestGoodnessOfFit);