name: Build Pipeline v2.1

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "**/*.md"
      - "**/.gitignore"
      - "assets/*"
      - "source/PerformanceTests/*"
      - "source/PerformanceTestingConsoleApp/*"
      - "**/site/*"
      - "/site/*"
    # Include workflow file changes to trigger CI/CD when versioning changes
    paths:
      - ".github/workflows/build-v2.1.yml"

  pull_request:
    types: [ opened, synchronize, reopened ]
    paths-ignore:
      - "**/*.md"
      - "**/.gitignore"
      - "assets/*"
      - "source/PerformanceTests/*"
      - "source/PerformanceTestingConsoleApp/*"
      - "**/site/*"
      - "/site/*"

  workflow_dispatch:

jobs:
  set_version:
    name: Set Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract_version.outputs.full_version }}
      version_prefix: ${{ steps.extract_version.outputs.version_prefix }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Extract version from workflow filename
        id: extract_version
        run: |
          # Get the workflow file path from GITHUB_WORKFLOW_REF
          WORKFLOW_PATH=${GITHUB_WORKFLOW_REF#refs/}
          WORKFLOW_FILENAME=$(basename "$WORKFLOW_PATH")
          
          # Extract major.minor from filename (build-v2.1.yml -> 2.1)
          VERSION_PREFIX=$(echo $WORKFLOW_FILENAME | grep -oP 'v\K[0-9]+\.[0-9]+')
          
          # Use github.run_number as build/patch number
          BUILD_NUMBER=${{ github.run_number }}
          
          # Combine to form full version
          FULL_VERSION="$VERSION_PREFIX.$BUILD_NUMBER"
          
          # Add suffix for pull requests
          if [ "${{ github.ref }}" != "refs/heads/main" ]; then
            FULL_VERSION="$FULL_VERSION-pull-request"
          fi
          
          echo "version_prefix=$VERSION_PREFIX" >> $GITHUB_OUTPUT
          echo "full_version=$FULL_VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $FULL_VERSION"

  build:
    name: Build
    needs: set_version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [ "Sailfish" ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.x.x
            9.x.x

      - name: Update version in project files
        run: |
          # Update version in all three main project files
          sed -i "s/<Version>.*<\/Version>/<Version>${{ needs.set_version.outputs.version }}<\/Version>/" source/Sailfish/Sailfish.csproj
          sed -i "s/<Version>.*<\/Version>/<Version>${{ needs.set_version.outputs.version }}<\/Version>/" source/Sailfish.TestAdapter/Sailfish.TestAdapter.csproj
          sed -i "s/<Version>.*<\/Version>/<Version>${{ needs.set_version.outputs.version }}<\/Version>/" source/Sailfish.Analyzers/Sailfish.Analyzers.csproj
          
          # Verify the changes
          echo "Updated Sailfish.csproj version:"
          grep "<Version>" source/Sailfish/Sailfish.csproj
          echo "Updated Sailfish.TestAdapter.csproj version:"
          grep "<Version>" source/Sailfish.TestAdapter/Sailfish.TestAdapter.csproj
          echo "Updated Sailfish.Analyzers.csproj version:"
          grep "<Version>" source/Sailfish.Analyzers/Sailfish.Analyzers.csproj

      - name: Build Projects
        run: |
          dotnet build ./source/Sailfish/Sailfish.csproj --configuration Release
          dotnet build ./source/Sailfish.TestAdapter/Sailfish.TestAdapter.csproj --configuration Release
          dotnet build ./source/Sailfish.Analyzers/Sailfish.Analyzers.csproj --configuration Release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: built-binaries
          path: |
            source/Sailfish/bin/Release/**
            source/Sailfish.TestAdapter/bin/Release/**
            source/Sailfish.Analyzers/bin/Release/**
          retention-days: 1

  test:
    name: Unit Tests
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [ "Tests.Library", "Tests.TestAdapter", "Tests.Analyzers" ]
    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.x.x
            9.x.x

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: built-binaries

      - name: Test Projects
        run: dotnet test ./source/${{ matrix.project }}/${{ matrix.project }}.csproj --verbosity normal --collect:"XPlat Code Coverage"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: paulegradie/Sailfish

  pack:
    name: Nuget Package Test
    needs: [ test, set_version ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [ "Sailfish", "Sailfish.TestAdapter", "Sailfish.Analyzers" ]
    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.x.x
            9.x.x

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: built-binaries
          path: source/

      - name: Restore Dependencies
        run: dotnet restore ./source/${{matrix.project}}/${{matrix.project}}.csproj

      - name: Pack Projects
        run: dotnet pack ./source/${{matrix.project}}/${{matrix.project}}.csproj --configuration Release --no-build --output .

      - name: Verify Package Exists
        run: |
          if [ ! -f "${{matrix.project}}.${{ needs.set_version.outputs.version }}.nupkg" ]; then
            echo "Package file not found: ${{matrix.project}}.${{ needs.set_version.outputs.version }}.nupkg"
            exit 1
          fi
          echo "Package file found: ${{matrix.project}}.${{ needs.set_version.outputs.version }}.nupkg"

      - name: Push Packages to Nuget
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: dotnet nuget push ${{matrix.project}}.${{ needs.set_version.outputs.version }}.nupkg --source https://www.nuget.org --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate

  sonar:
    name: Sonar Code Quality Check
    needs: [ set_version, build ]
    runs-on: windows-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "zulu"
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner
      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          .\.sonar\scanner\dotnet-sonarscanner begin /k:"sailfish_library" /o:"sailfish" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
          dotnet build ./source
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
