name: Test, Pack and Publish to nuget
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "**/*.yml"
      - "**/.gitignore"
      - "assets/*"
      - "source/PerformanceTests/*"
      - "source/PerformanceTestingConsoleApp/*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Checkout
        uses: actions/checkout@v2

      - name: Precheck version
        run: echo ${VERSION}

      - name: Set version
        run: echo "VERSION=0.1.${{ github.run_number }}" >> $GITHUB_ENV

      - name: Test version (write)
        run: echo ${VERSION}

      - name: Build
        run: dotnet build ./source/Sailfish/Sailfish.csproj --configuration Release /p:Version=${{ env.VERSION }}

      - name: Build Test Adapter
        run: dotnet build ./source/Sailfish.TestAdapter/Sailfish.TestAdapter.csproj --configuration Release /p:Version=${{ env.VERSION }}

      - name: Test
        run: dotnet test ./source/Tests.Sailfish/Tests.Sailfish.csproj --verbosity normal

      - name: Test Adapter
        run: dotnet test ./source/Tests.Sailfish.TestAdapter/Tests.Sailfish.TestAdapter.csproj --verbosity normal

      - name: Pack
        run: dotnet pack ./source/Sailfish/Sailfish.csproj --configuration Release /p:Version=${{ env.VERSION }} --no-build --output .

      - name: Push
        run: dotnet nuget push Sailfish.${{ env.VERSION }}.nupkg --source https://www.nuget.org --api-key ${{secrets.NUGET_API_KEY}}

      - name: Pack Adapter
        run: dotnet pack ./source/Sailfish.TestAdapter/Sailfish.TestAdapter.csproj --configuration Release /p:Version=${{ env.VERSION }} --no-build --output .

      - name: Push Adapter
        run: dotnet nuget push Sailfish.TestAdapter.${{ env.VERSION }}.nupkg --source https://www.nuget.org --api-key ${{secrets.NUGET_API_KEY}}
